"project_id": "462384"                     #open project settings and go to API section 
"api_token": "1e982226beb46a10d05de9a88c3a0c5586a7ee3285db25764edf6e6f86d7e6ee619dbc043cb91a90"          #open profile settings and go to API & SSO > New Token > create Token
"base_path": "/axiwiki"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files": [
  {
    "source": "/*",                                       #source files filter
    "translation": "/%two_letters_code%/%original_file_name%"        #where translations are stored
  }
]
