project_id: '462384'
api_token_env: 'CROWDIN_TOKEN'
base_path: /
base_url: 'https://api.crowdin.com'
preserve_hierarchy: true
files:
  - source: /*
    translation: /%two_letters_code%/%original_file_name%
